### ISSUE TITLE
Settings Not Saving After Exiting TFM

### ISSUE THREAD

**Issue by kev5688** [jfayre/talking-flight-monitor-net#101]
Hi there. If I go into the settings dialog in TFM, tools>settings, and make a change, I can hit ok, and go back into the dialog, and the change will be made. For example, changing the default pmdg hotkeys from control and alt to function keys. Or checking the minimize to system tray. However, once I exit TFM and go back into it, those changes aren't saved. I've tried running it as administrator, and also reinstalling, but it seems even uninstalling doesn't delete my settings. Was wondering where my settings are stored so that I could delete that file and maybe start from scratch, as I'm thinking but not sure that's what it could be. I've also scanned my logfile, but I'm not seeing any errors, however I can attach it here if that helps. Thank you for your hard work and dedication with TFM, it is greatly appreciated.

**Comment by jfayre** [comment]
Hello,

Deleting your settings and starting over should solve this. The settings are in:

C:\Users\<your username>\AppData\Local\tfm

 

We think we’ve figured out what is causing this. It should be updated in a future build.

 

 

 

 

From: kev5688 ***@***.***> 
Sent: May 23, 2021 12:20 PM
To: jfayre/talking-flight-monitor-net ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jfayre/talking-flight-monitor-net] Settings Not Saving After Exiting TFM (#101)

 

Hi there. If I go into the settings dialog in TFM, tools>settings, and make a change, I can hit ok, and go back into the dialog, and the change will be made. For example, changing the default pmdg hotkeys from control and alt to function keys. Or checking the minimize to system tray. However, once I exit TFM and go back into it, those changes aren't saved. I've tried running it as administrator, and also reinstalling, but it seems even uninstalling doesn't delete my settings. Was wondering where my settings are stored so that I could delete that file and maybe start from scratch, as I'm thinking but not sure that's what it could be. I've also scanned my logfile, but I'm not seeing any errors, however I can attach it here if that helps. Thank you for your hard work and dedication with TFM, it is greatly appreciated.
