### ISSUE TITLE
alt intervene and speed intervene lights don't appear ot say on or off.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#104]
**Describe the bug**

        when I'm evoking alt intervene and speed intervene I don't hear weather they are on or off.

**To Reproduce**

1. turn on alt intervene or speed intervene
2. This is when the indications if any should say on or off, if they have lights.

**Expected behavior**

I should , I believe be able to "see" if they are on or off. I can't even see  this in the MCP.

**additional information
 - OS: [e.g. Windows 10] windows 10
 - TFM version:  alpha 2.16
 - Flight simulator in use:  prepar3dv4
- specific aircraft in use: pmdg 737 ngxu

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.

**Comment by jfayre** [comment]
It doesn't look like there is a specific light for Altitude Intervene. There are some messages that come up in the PMDG aircraft that they don't expose through the SDK. There does appear  to be a light for Speed though. I'll check to see if we're monitoring that.

**Comment by jfayre** [comment]
Turns out we're already monitoring the speed light. It's possible this doesn't light up when speed intv is on.

**Comment by marrie** [comment]
Maybe. I hear the click but in the heat of the moment shall we say, it 
can be hard to remember, did I turn that on? Or didn't I? I'm not quite 
sure what to di in that regard.

**Comment by ajborka** [comment]
The speed light is not speed intv. On the 737, it is a thrust mode similar to speed hold. There aren't any methods available to track speed, altitude, or heading intv. presses because they are momentary push buttons. Example in your typical household is when you press the power button on your laptop. It pushes in, makes a contact to complete an electrical circuit, then releases to the original state (depressed) when you let go of the button. Not really a way of tracking those, which oddly enough is giving me problems in the 777 with speed modes :(. Closing this since there isn't any recorse.
