### ISSUE TITLE
bug: speed inv does not read when toggling between mcp and inv modes

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#116]
**Describe the bug**

when I hit speed inv from  the sim or from tfm I don't hear it auto read the speed, instead I hear "speed box visible  and speed box blank. when I check with tfm plus s, ank I see the fmc speed and something else when speed inv is off.

**To Reproduce**

1. turn on speed inv from the sim or from the speed box.
2. check what tfm plus s says.
3. repeat step 1 and 2
4. notice speed is not auto read.

**Expected behavior**

I think I should hear the speeds read automatically. I don't mind using tfm plus s, if this behavior is intended. 

**additional information
 - OS: [e.g. Windows 10] Windows 10 21H1 (x64) build 19043.1165
 - TFM version: 18.1
 - Flight simulator in use:  prepar3dv4.5
- specific aircraft in use: pmdg737 house

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.

attached is a [vid](https://www.dropbox.com/s/h1lie41i4xi28ym/tfm%2018.2%20speed%20box%20blank%20bug.mkv?dl=1) of the issue.

**Comment by ajborka** [comment]
This is expected behavior from the new speed box setup. When toggling speed intervene, the 737 will do one of 2 things:

1. Give control of the speed to the FMC so it can manage the intended flight path, known as FMC speed in TFM, or
2. Give the pilot control of the speed, known as MCP speed in TFM.
When turning on speed intervene (MCP speed), TFM doesn't automatically announce the current speed because it hasn't changed from the previously managed FMC speed. TFM will only announce a speed change when turning on speed intervene when the new recommended speed is different from the current FMC speed. Example: At cruise, you are at mach 0.78. When you start your descent, you turn on speed intervene to manage the maximum allowable descent speed. TFM will announce the new speed as speed intervene turns on because the new target speed is much less than mach 0.78. Instead, it is now 290 (around mach 0.65). On the other hand, the speed box visible announcement can be confusing, so will change it for the next release.

**Comment by marrie** [comment]
Ah Ok. Thanks. I was not sure, so thought I’d ask. I was expecting that to auto read, as I’ve actually been having this issue since 17.4.
