### ISSUE TITLE
VFR flying.

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor-net#25]
As we progress through the development cycle, I'd like to see TFM have the ability to fly VFR flights.
This would require the ability for it to read from the navigational table, and you would for example take off, (manually liek you already do) but instead of having a plan, your auto pilot it set to go direct to a destination like KCLT. The landing sequence I'm not sure how we'd make that happen, but FSX does traffic patterns, rather shittily, mind you, but that's a way you could land it, but we shold make it so that if a controller wants you to turn base that ability is their.
I'm probably making no sense but hopefully some of this makes sense.

**Comment by ajborka** [comment]
The definition of VFR is when the weather is clear enough for a pilot to see what the plane is doing, and where he/she is going. Usually VFR flying puts more focus on the visual aspects of the environment, and less on the instrument panels. For example, it is not allowed to use a radar to detect other aircraft. The pilot must visually identify the other airplanes in the area. Although some instruments may have a factor in VFR such as altitude, the pilot is still responsible for guestimating his/her altitude by looking out the window. The altitude gage in this case is only for verification in the event weather gets poor enough to revert to ifr, on landing when altitude is a life-death issue, or ATC requests an official readout. Otherwise, instruments aren't normally used. The definition of autopilot is an automated computerized process that uses the airplane's instruments, systems, and other navigational aids to successfully fly the plane from point A to point B. Autopilot and VFR aren't usually compatible for those reasons. Since VFR is mostly flying based on what the pilot can see out the windows, we can't implement VFR flying.

**Comment by jfayre** [comment]
It may be possible to add some aspects of VFR flying in the future such as flying direct to an airport, and turning on base and lining up for a runway. I know a few people in the community use FSX Pilot for flying GA aircraft, but I'm not aware of everything that would be required to make TFM duplicate that functionality.
