### ISSUE TITLE
bug: Pressing right bracket triggers TFM when other applications have focus

### ISSUE THREAD

**Issue by ajborka** [jfayre/talking-flight-monitor-net#35]
**Describe the bug**
When the simulator or TFM is not in focus, TFM keyboard shortcuts still work. EX: When typing out a bug report a few minutes ago, I had to spell out the TFM command because pressing the key triggered TFM since there is a flight in the background.

**To Reproduce**
1. Start a flight
2. Start TFM
3. Minimize TFM and the flight to the background
4. Do something else like browse websites or check email.

**Expected behavior**
TFM would ignore the TFM command outside of simulator/TFM windows unless the user grants permission for TFM to hijack the right bracket key.

**Comment by ajborka** [comment]
I know, but it is annoying when trying to type code or other things outside the simulator, and get blocked because ] is locked up with something else.

**Comment by marrie** [comment]
Can there be a key you can press to disable the tfm right bracket and enable it again when back inside the app when you are done to resume normal behavior?

**Comment by jfayre** [comment]
That’s definitely workable. I’m thinking a double press of the right bracket to disable it.

There was also some talk of a mode where the TFM keys stay locked on. Kind of a layered key mode. That’s also easy to do.

**Comment by marrie** [comment]
I like the double press of the bracket key actually. In fact I do that 
by instinct. So right bracket right bracket, then, what, a third right 
bracket to enter the key? If we did that, would there then be a time out 
where if you did not double press the right bracket, or tfm key within a 
certain amount if time, it would reenable? I think I have my logic 
backward on this one actually. I know how I would like this implemented, 
but I'm not sure how to put this in words. The closest thing I can think 
of would be a delay time out where:

* if the double bracket is pressed with in x ms or S, disable the tfm  
keys to allow input, otherwise
* execute the command(s) you wanted if the double bracket is pressed too 
slowly, that is, outside the time range.

# Example
  A user presses  double right bracket twice by accident. If the user 
waits x seconds, or ms,  they can try again with the single right 
bracket otherwise

**Comment by jfayre** [comment]
I just added the double press right bracket in build 84.

There is no time out, so pressing right bracket twice just kills command mode until you re-enable it by going into the tfm window and pressing Ctrl+Shift+c. The option to toggle command mode is also on the tfm tools menu.

**Comment by ajborka** [comment]
This is fixed.
