### ISSUE TITLE
bug: City Viewing Function is Broken

### ISSUE THREAD

**Issue by taljazz** [jfayre/talking-flight-monitor-net#81]
For some reason I am having some problems viewing a city I am near. I will post a log entry below
tfm.IOSubsystem.onCityKey - error retrieving nearest city: The underlying connection was closed: An unexpected error occurred on a receive.
tfm.IOSubsystem.onCityKey - error retrieving oceanic info: The underlying connection was closed: An unexpected error occurred on a receive.

**Comment by ajborka** [comment]
@taljazz  there isn't anything we can do to help the connection to the online web service. If it goes down or refuses the connection, you will have to try again later. Does this happen all the time, or only part of the time? What city is it you are trying to see?

**Comment by obert01** [comment]
Hello,

Some issues with the City Viewing / Where am I feature may be  due to a long-standing issue in BingMapsSDSToolkit:
https://github.com/microsoft/BingMapsSDSToolkit/issues/5

This problem occurs on systems where the decimal separator is not set to "." (dot) in Windows regional format settings. It is the case at least in France where the decimal separator is "," (coma). This causes BingMapsSDSToolkit to send improperly formatted lattitude and longitude to the API. 

If you encounter this issue, a quick workaround is to change your Windows regional format settings to English before launching TFM. 

Hope that helps.

**Comment by ajborka** [comment]
I will look into this. A possible workaround is to set the current thread's decimal seperator to the one En-us uses, then change it back to the one used by Windows as identified in the original post.

**Comment by marrie** [comment]
I was I think over Budapest  today and I got "error getting the closest city, see log." then I tried tfm plus shift c, and I got the dreded quit and details and continue error. I have my log from that session I hope which I will attach. I wonder if this in fact is the same issue.
[tfm.log](https://github.com/jfayre/talking-flight-monitor-net/files/6388135/tfm.log)

Thanks.

**Comment by trodick** [comment]
The end of this log says "error resolving..." This means an Internet issue.

**Comment by marrie** [comment]
That might explain it then. I also got the details dialogue when I had full internet though, I was still able to complete my flight, I just for those few seconds  could not tell where I was.

**Comment by ajborka** [comment]
After looking at the log, it appears there is no active internet connection, or the geonames service went down for a time. Try it again later tonight or tomorrow.

**Comment by obert01** [comment]
Hello,

Warning: This issue should not be closed, as there is still a bug in the city viewing function, that happens when the Windows language is not set to English (see my previous post in the thread). 

I don't think this has been fixed yet.

**Comment by ajborka** [comment]
This is a Bing maps problem. The API doesn't understand GPS coordinates such as 82,332,01,552 instead of 82.332,01.552. The first example is used in Windows environments other than US English. The last example is a properly formatted pair according to US standards. Since Bing maps isn't interested in fixing the problem, we can look at a workaround, but it might take some time.

**Comment by ajborka** [comment]
Closing this because it seems to be a BingMaps API problem, and we can't fix upstream issues.
