### ISSUE TITLE
Over speed warnings

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor-net#91]
When the over speed warning starts, it some times doesnt stop saying over speed warning. Maybe if we could have some type of toggle key to make it stop saying over speed after it alerts us.

**Comment by ajborka** [comment]
@BviPilots  the overspeed warnings are generated with SAPI voices. As a result, we don't have control over when it stops. Basically, it reads everything in the queue until there is nothing left to read. If your overspeed warnings continue for some time, then SAPI will read them for some time after the overspeed warning stops. We were asked to have SAPI read them because it would be impossible to miss the announcements or turn them off in the event a pilot gets annoyed with them. After all, you can't really stop the overspeed warnings in an airplane until you stop speeding.
