### ISSUE TITLE
shift C sometimes returns the following message

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor-net#95]
'unhandled exception has occurred in your application. if you click continue, the application will ignore this error and attempt to continue. Object reference not set to an instance of an object.'

Often happens when , but not limited to, Asia. In this particular moment I am in Syria and it is happening. Does not happen with the C command only

**Comment by marrie** [comment]
I've seen this. I can't remember where I was when it happened.

**Comment by trodick** [comment]
@blindflightsimmer, can you please copy and paste the full exception text into the issue? If you get this again, click Details, then down arrow until you land in a read-only edit box. Press CTRL+A to select all, then copy/paste the contents of the box into a comment. I may be able to try and fix it and submit a PR if I have that available. Thanks.

**Comment by ajborka** [comment]
It is a NullReferenceException that happens when there isn’t any information returned from the sds web service. Nothing is returned when either or both of the following happen:

 

1.	The administrator who submitted information for the area in question actually submitted nothing, or a portion of what was requested.
2.	The current culture of the Windows 10 installation is something other than English – United States.

We will need to investigate the problem and try some possible fixes depending on the results. At this point, we will have to push it to the backlog and handle it later.

**Comment by marrie** [comment]
Well, the good thing is, it does not crash the app, so I don’t really  mind waiting for now.

 

Thanks.

**Comment by blindflightsimmer** [comment]
Well we still have the C key which never fails and is reliable. It seems to happen with special characters more often than not. When it happens again I will post the full message from details.

Sent from Mail for Windows 10

**Comment by trodick** [comment]
> It is a NullReferenceException that happens when there isn’t any information returned from the sds web service. Nothing is returned when either or both of the following happen: 1. The administrator who submitted information for the area in question actually submitted nothing, or a portion of what was requested. 2. The current culture of the Windows 10 installation is something other than English – United States. We will need to investigate the problem and try some possible fixes depending on the results. At this point, we will have to push it to the backlog and handle it later.
@ajborka Could we work around it for now by wrapping the call in a try/catch block, and perhaps just giving the "nothing found" message or something similar when it errors out, such that the user is not presented with a scary-looking dialog? That's a band-aid, as it were, and I'd happily write that in for the time being.

**Comment by trodick** [comment]
Can you please post the full exception text? Click Details in the exception dialog when you get it, and then arrow down to the read-only edit box. Copy and paste everything you see in that box into this issue. Thanks.

Sent from Mail for Windows 10

**Comment by blindflightsimmer** [comment]
Yeah, I will do when I next get it. 

Sent from Mail for Windows 10

**Comment by marrie** [comment]
Is this what you all were looking for? I was landing at, and stopped at SBBR, and got this.

 

See the end of this message for details on invoking 

just-in-time (JIT) debugging instead of this dialog box.

 

************** Exception Text **************

System.NullReferenceException: Object reference not set to an instance of an object.

   at tfm.IOSubsystem.<onCurrentLocation>d__184.MoveNext() in C:\projects\talking-flight-monitor-net\source\IOSubsystem.cs:line 2699

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

 

 

************** Loaded Assemblies **************

mscorlib

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

----------------------------------------

tfm

    Assembly Version: 1.0.0.0

    Win32 Version: 1.0.0.0

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/tfm.exe

----------------------------------------

System.Windows.Forms

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

----------------------------------------

System

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------

System.Drawing

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

----------------------------------------

NLog

    Assembly Version: 4.0.0.0

    Win32 Version: 4.7.6.12219

    CodeBase: file:///C:/Program%20Files/talking%20flight%20monitor/NLog.DLL

----------------------------------------

System.Speech

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll

----------------------------------------

System.Configuration

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

----------------------------------------

System.Core

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

----------------------------------------

System.Xml

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4084.0 built by: NET48REL1

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

----------------------------------------

System.Data

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

----------------------------------------

System.ServiceModel

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll

----------------------------------------

System.Runtime.Serialization

    Assembly Version: 4.0.0.0

    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C

    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

----------------------------------------

FSUIPCClient

    Assembly Version: 3.1.25.341

    Win32 Version: 3.1.25.341

    CodeBase: file:///C:/Program%20Files/talking
